"""Convert the Azure Functions 2019 dataset into simulator inputs.

Input: the extracted dataset directory (from
azurefunctions_dataset2019_azurefunctions-dataset2019.tar.xz), containing
per-day files:
  - invocations_per_function_md.anon.dNN.csv  (per-minute counts, 1440 cols)
  - function_durations_percentiles.anon.dNN.csv (ms percentiles per function)
  - app_memory_percentiles.anon.dNN.csv (MB percentiles per app)

Output, per selected function:
  - <out>/rate_<n>.csv - the simulator's rate-trace format (t, rate in
    tasks/second, one sample per minute) for the `trace` rate pattern.
  - <out>/generator_snippets.yaml - ready-to-paste generator blocks with
    the rate trace file plus `percentile` distribution specs for
    cpu_demand (derived from duration percentiles; scaled ms -> work
    units at 1 work unit per second of measured runtime) and
    memory_demand (from the app's memory percentiles, scaled MB -> the
    simulator's abstract memory units at 1 unit per GB).

Functions are selected as the top-N by daily invocations among those with
at least `--min-invocations` (default 500) - busy enough to give a real
arrival rhythm. Use --day to pick the dataset day (01..14; memory files
exist for 01..12).

Usage:
    python tools/prepare_azure_functions.py resources/datasets/azure_functions \
        resources/datasets/processed/azure --top 3 --day 1
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

_PCT_COLUMNS = [
    ("percentile_Average_0", 0),
    ("percentile_Average_1", 1),
    ("percentile_Average_25", 25),
    ("percentile_Average_50", 50),
    ("percentile_Average_75", 75),
    ("percentile_Average_99", 99),
    ("percentile_Average_100", 100),
]

_MEM_PCT_COLUMNS = [
    ("AverageAllocatedMb_pct1", 1),
    ("AverageAllocatedMb_pct5", 5),
    ("AverageAllocatedMb_pct25", 25),
    ("AverageAllocatedMb_pct50", 50),
    ("AverageAllocatedMb_pct75", 75),
    ("AverageAllocatedMb_pct95", 95),
    ("AverageAllocatedMb_pct99", 99),
    ("AverageAllocatedMb_pct100", 100),
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("dataset_dir", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--day", type=int, default=1, help="dataset day (1-12)")
    parser.add_argument("--top", type=int, default=3,
                        help="number of functions to extract")
    parser.add_argument("--min-invocations", type=int, default=500)
    parser.add_argument("--max-invocations", type=int, default=None,
                        help="skip busier functions (keeps edge-scale rates)")
    args = parser.parse_args(argv)

    day = f"d{args.day:02d}"
    inv_path = args.dataset_dir / f"invocations_per_function_md.anon.{day}.csv"
    dur_path = args.dataset_dir / f"function_durations_percentiles.anon.{day}.csv"
    mem_path = args.dataset_dir / f"app_memory_percentiles.anon.{day}.csv"
    for p in (inv_path, dur_path, mem_path):
        if not p.is_file():
            raise SystemExit(f"error: missing {p}")

    minute_cols = [str(m) for m in range(1, 1441)]

    # Duration percentiles per function; memory percentiles per app.
    durations: dict[str, list[tuple[int, float]]] = {}
    with dur_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            durations[row["HashFunction"]] = [
                (pct, float(row[col])) for col, pct in _PCT_COLUMNS
            ]
    memory: dict[str, list[tuple[int, float]]] = {}
    with mem_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            memory[row["HashApp"]] = [
                (pct, float(row[col])) for col, pct in _MEM_PCT_COLUMNS
            ]

    # Rank functions that have all the pieces.
    candidates: list[tuple[int, str, str, str, list[int]]] = []
    with inv_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            func = row["HashFunction"]
            if func not in durations or row["HashApp"] not in memory:
                continue
            counts = [int(row[m]) for m in minute_cols]
            total = sum(counts)
            if total < args.min_invocations:
                continue
            if args.max_invocations is not None and total > args.max_invocations:
                continue
            candidates.append((total, func, row["HashApp"], row["Trigger"], counts))
    if not candidates:
        raise SystemExit("error: no functions matched the selection criteria")
    candidates.sort(key=lambda c: (-c[0], c[1]))
    chosen = candidates[: args.top]

    args.output_dir.mkdir(parents=True, exist_ok=True)
    snippets: list[str] = [
        "# Generated by tools/prepare_azure_functions.py - paste into a node's",
        "# source.generator block. Data: Azure Functions 2019 (day %s)." % day,
        "# cpu_demand scale: 1 work unit per second of measured duration.",
        "# memory scale: 1 memory unit per GB allocated.",
        "",
    ]
    for i, (total, func, app, trigger, counts) in enumerate(chosen, start=1):
        rate_file = args.output_dir / f"rate_{i}.csv"
        with rate_file.open("w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f, lineterminator="\n")
            writer.writerow(["t", "rate"])
            for minute, count in enumerate(counts):
                writer.writerow([minute * 60, count / 60.0])

        dur_points = ", ".join(f"[{p}, {v}]" for p, v in durations[func])
        mem_points = ", ".join(f"[{p}, {v}]" for p, v in memory[app])
        snippets += [
            f"# --- function {i}: trigger={trigger}, "
            f"{total} invocations/day, hash={func[:12]}... ---",
            "generator:",
            "  type: poisson",
            f"  rate: {{pattern: trace, file: {rate_file.as_posix()}}}",
            f"  task_type: {trigger}",
            f"  cpu_demand: {{dist: percentile, points: [{dur_points}], "
            "scale: 0.001}",
            f"  memory_demand: {{dist: percentile, points: [{mem_points}], "
            "scale: 0.001}",
            "  data_size: 100000        # not in the dataset: synthetic, document it",
            "  result_size: 10000       # not in the dataset: synthetic, document it",
            "  deadline_offset: 30.0    # not in the dataset: synthetic, document it",
            "",
        ]

    snippet_path = args.output_dir / "generator_snippets.yaml"
    snippet_path.write_text("\n".join(snippets), encoding="utf-8")
    print(f"wrote {len(chosen)} rate traces + {snippet_path}")
    for i, (total, func, _, trigger, _) in enumerate(chosen, start=1):
        print(f"  rate_{i}.csv: {trigger} function, {total} invocations/day")
    return 0


if __name__ == "__main__":
    sys.exit(main())
